apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "../base"

patches:
  - target:
      kind: Ingress
      name: keycloak
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: keycloak.workload-1.example.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: keycloak.workload-1.example.com