---
apiVersion: infrastructure.cluster.konvoy.d2iq.io/v1alpha1
kind: PreprovisionedInventory
metadata:
  name: nkp-b300-nai-control-plane
  namespace: edge-clusters
  labels:
    cluster.x-k8s.io/cluster-name: nkp-b300-nai 
    clusterctl.cluster.x-k8s.io/move: ""
spec:
  hosts:
    - address: 10.5.233.197
    - address: 10.5.233.198
    - address: 10.5.233.199
  sshConfig:
    port: 22
    user: nutanix 
    privateKeyRef:
      name: nkp-b300-nai-ssh-key 
      namespace: edge-clusters
---
apiVersion: infrastructure.cluster.konvoy.d2iq.io/v1alpha1
kind: PreprovisionedInventory
metadata:
  name: nkp-b300-nai-md-0
  namespace: edge-clusters 
  labels:
    cluster.x-k8s.io/cluster-name: nkp-b300-nai
    clusterctl.cluster.x-k8s.io/move: ""
spec:
  hosts:
    - address: 10.5.233.200
    - address: 10.5.233.201
    - address: 10.5.233.202
    - address: 10.5.233.203
  sshConfig:
    port: 22
    user: nutanix
    privateKeyRef:
      name: nkp-b300-nai-ssh-key
      namespace: edge-clusters
